/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mateu
 */
public class TelaHome extends javax.swing.JFrame {
    
    public String nomeLogado;
    public String tipoLogado;
    
    public frmUsuario telaUsuario = new frmUsuario();

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        itemMenuControleUsuarios = new javax.swing.JMenuItem();
        menuVideos = new javax.swing.JMenu();
        itemMenuControleVideos = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        itemMenuSair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a16user (3).png"))); // NOI18N
        menuUsuarios.setText("Usuarios");

        itemMenuControleUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userb-16.png"))); // NOI18N
        itemMenuControleUsuarios.setText("Controle de usuários");
        itemMenuControleUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuControleUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemMenuControleUsuarios);

        jMenuBar1.add(menuUsuarios);

        menuVideos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a16play (1).png"))); // NOI18N
        menuVideos.setText("Vídeos");

        itemMenuControleVideos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/videob-16.png"))); // NOI18N
        itemMenuControleVideos.setText("Controle de vídeos");
        itemMenuControleVideos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuControleVideosActionPerformed(evt);
            }
        });
        menuVideos.add(itemMenuControleVideos);

        jMenuBar1.add(menuVideos);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear16.png"))); // NOI18N
        menuSistema.setText("Sistema");

        itemMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout2-16.png"))); // NOI18N
        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuSistema.add(itemMenuSair);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        // Logout
        Object[] options = { "Sim", "Não" };
        
        int p = JOptionPane.showOptionDialog(null, "Deseja realmente sair do sistema?", "Sair",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, 
                options, options[0]);
                
        if(p == JOptionPane.YES_OPTION){
            frmNovoLogin login = new frmNovoLogin();
            nomeLogado = "";
            tipoLogado = "";
            //telaVideo.dispose();
            telaUsuario.dispose();
            this.dispose();
            login.setVisible(true);
        }
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void itemMenuControleVideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuControleVideosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuControleVideosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void itemMenuControleUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuControleUsuariosActionPerformed
        //Item controle usuarios
        //telaVideos.dispose();as
        telaUsuario.setVisible(true);
    }//GEN-LAST:event_itemMenuControleUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem itemMenuControleUsuarios;
    public javax.swing.JMenuItem itemMenuControleVideos;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu menuSistema;
    public javax.swing.JMenu menuUsuarios;
    public javax.swing.JMenu menuVideos;
    // End of variables declaration//GEN-END:variables
}
